export type BehanceProject = {
  slug: string;
  title: string;
  url: string;
  coverImage: string;
  images: string[];
  moduleCount: number;
};

export const behanceProjects: BehanceProject[] = [
  {
    "slug": "REFLECT-Furniture-design",
    "title": "REFLECT | Furniture design",
    "url": "https://www.behance.net/gallery/127793335/REFLECT-Furniture-design",
    "coverImage": "/behance/REFLECT-Furniture-design/cover.png",
    "images": [
      "/behance/REFLECT-Furniture-design/1.png",
      "/behance/REFLECT-Furniture-design/2.png",
      "/behance/REFLECT-Furniture-design/3.png",
      "/behance/REFLECT-Furniture-design/4.png",
      "/behance/REFLECT-Furniture-design/5.jpg",
      "/behance/REFLECT-Furniture-design/6.png",
      "/behance/REFLECT-Furniture-design/7.png",
      "/behance/REFLECT-Furniture-design/8.png",
      "/behance/REFLECT-Furniture-design/9.png",
      "/behance/REFLECT-Furniture-design/10.png",
      "/behance/REFLECT-Furniture-design/11.png",
      "/behance/REFLECT-Furniture-design/12.png",
      "/behance/REFLECT-Furniture-design/13.png",
      "/behance/REFLECT-Furniture-design/14.png",
      "/behance/REFLECT-Furniture-design/15.png",
      "/behance/REFLECT-Furniture-design/16.png",
      "/behance/REFLECT-Furniture-design/17.png",
      "/behance/REFLECT-Furniture-design/18.png",
      "/behance/REFLECT-Furniture-design/19.png",
      "/behance/REFLECT-Furniture-design/20.png",
      "/behance/REFLECT-Furniture-design/21.jpg",
      "/behance/REFLECT-Furniture-design/22.png",
      "/behance/REFLECT-Furniture-design/23.png",
      "/behance/REFLECT-Furniture-design/24.png",
      "/behance/REFLECT-Furniture-design/25.png",
      "/behance/REFLECT-Furniture-design/26.png",
      "/behance/REFLECT-Furniture-design/27.png",
      "/behance/REFLECT-Furniture-design/28.png"
    ],
    "moduleCount": 28
  },
  {
    "slug": "D-L-speaker-product-design",
    "title": "D&L speaker | product design",
    "url": "https://www.behance.net/gallery/127801319/D-L-speaker-product-design",
    "coverImage": "/behance/D-L-speaker-product-design/cover.png",
    "images": [
      "/behance/D-L-speaker-product-design/1.png",
      "/behance/D-L-speaker-product-design/2.png",
      "/behance/D-L-speaker-product-design/3.png",
      "/behance/D-L-speaker-product-design/4.png",
      "/behance/D-L-speaker-product-design/5.png",
      "/behance/D-L-speaker-product-design/6.png",
      "/behance/D-L-speaker-product-design/7.png",
      "/behance/D-L-speaker-product-design/8.png",
      "/behance/D-L-speaker-product-design/9.png",
      "/behance/D-L-speaker-product-design/10.png",
      "/behance/D-L-speaker-product-design/11.png",
      "/behance/D-L-speaker-product-design/12.png"
    ],
    "moduleCount": 12
  },
  {
    "slug": "Bottle-design",
    "title": "Bottle design",
    "url": "https://www.behance.net/gallery/132124675/Bottle-design",
    "coverImage": "/behance/Bottle-design/cover.jpg",
    "images": [
      "/behance/Bottle-design/1.jpg",
      "/behance/Bottle-design/2.jpg",
      "/behance/Bottle-design/3.jpg",
      "/behance/Bottle-design/4.jpg",
      "/behance/Bottle-design/5.jpg",
      "/behance/Bottle-design/6.jpg",
      "/behance/Bottle-design/7.jpg",
      "/behance/Bottle-design/8.jpg",
      "/behance/Bottle-design/9.jpg",
      "/behance/Bottle-design/10.jpg",
      "/behance/Bottle-design/11.jpg",
      "/behance/Bottle-design/12.jpg",
      "/behance/Bottle-design/13.jpg",
      "/behance/Bottle-design/14.jpg",
      "/behance/Bottle-design/15.jpg",
      "/behance/Bottle-design/16.jpg",
      "/behance/Bottle-design/17.jpg",
      "/behance/Bottle-design/18.jpg",
      "/behance/Bottle-design/19.jpg",
      "/behance/Bottle-design/20.jpg",
      "/behance/Bottle-design/21.jpg",
      "/behance/Bottle-design/22.jpg",
      "/behance/Bottle-design/23.jpg",
      "/behance/Bottle-design/24.jpg",
      "/behance/Bottle-design/25.jpg"
    ],
    "moduleCount": 25
  },
  {
    "slug": "Travel-Bottle-carry-it-as-you-want",
    "title": "Travel Bottle- carry it as you want",
    "url": "https://www.behance.net/gallery/132126717/Travel-Bottle-carry-it-as-you-want",
    "coverImage": "/behance/Travel-Bottle-carry-it-as-you-want/cover.jpg",
    "images": [
      "/behance/Travel-Bottle-carry-it-as-you-want/1.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/2.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/3.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/4.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/5.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/6.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/7.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/8.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/9.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/10.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/11.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/12.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/13.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/14.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/15.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/16.jpg",
      "/behance/Travel-Bottle-carry-it-as-you-want/17.jpg"
    ],
    "moduleCount": 17
  },
  {
    "slug": "Black-Amber-logo-design",
    "title": "Black Amber | logo design",
    "url": "https://www.behance.net/gallery/138369665/Black-Amber-logo-design",
    "coverImage": "/behance/Black-Amber-logo-design/cover.png",
    "images": [
      "/behance/Black-Amber-logo-design/1.png",
      "/behance/Black-Amber-logo-design/2.png",
      "/behance/Black-Amber-logo-design/3.png",
      "/behance/Black-Amber-logo-design/4.png",
      "/behance/Black-Amber-logo-design/5.png",
      "/behance/Black-Amber-logo-design/6.png",
      "/behance/Black-Amber-logo-design/7.png",
      "/behance/Black-Amber-logo-design/8.png",
      "/behance/Black-Amber-logo-design/9.png",
      "/behance/Black-Amber-logo-design/10.png",
      "/behance/Black-Amber-logo-design/11.png",
      "/behance/Black-Amber-logo-design/12.png",
      "/behance/Black-Amber-logo-design/13.png",
      "/behance/Black-Amber-logo-design/14.png",
      "/behance/Black-Amber-logo-design/15.png"
    ],
    "moduleCount": 15
  },
  {
    "slug": "Poster-365-Practice",
    "title": "Poster 365 Practice",
    "url": "https://www.behance.net/gallery/167431223/Poster-365-Practice",
    "coverImage": "/behance/Poster-365-Practice/cover.jpg",
    "images": [
      "/behance/Poster-365-Practice/1.jpg",
      "/behance/Poster-365-Practice/2.jpg",
      "/behance/Poster-365-Practice/3.jpg",
      "/behance/Poster-365-Practice/4.jpg",
      "/behance/Poster-365-Practice/5.jpg",
      "/behance/Poster-365-Practice/6.jpg",
      "/behance/Poster-365-Practice/7.jpg",
      "/behance/Poster-365-Practice/8.jpg",
      "/behance/Poster-365-Practice/9.jpg",
      "/behance/Poster-365-Practice/10.jpg",
      "/behance/Poster-365-Practice/11.jpg",
      "/behance/Poster-365-Practice/12.jpg",
      "/behance/Poster-365-Practice/13.jpg",
      "/behance/Poster-365-Practice/14.jpg",
      "/behance/Poster-365-Practice/15.jpg",
      "/behance/Poster-365-Practice/16.jpg",
      "/behance/Poster-365-Practice/17.jpg"
    ],
    "moduleCount": 17
  },
  {
    "slug": "Moon-Festival-Package-Design",
    "title": "Moon Festival | Package Design",
    "url": "https://www.behance.net/gallery/170281711/Moon-Festival-Package-Design",
    "coverImage": "/behance/Moon-Festival-Package-Design/cover.png",
    "images": [
      "/behance/Moon-Festival-Package-Design/1.png",
      "/behance/Moon-Festival-Package-Design/2.png",
      "/behance/Moon-Festival-Package-Design/3.png",
      "/behance/Moon-Festival-Package-Design/4.png",
      "/behance/Moon-Festival-Package-Design/5.png",
      "/behance/Moon-Festival-Package-Design/6.jpg",
      "/behance/Moon-Festival-Package-Design/7.png",
      "/behance/Moon-Festival-Package-Design/8.png",
      "/behance/Moon-Festival-Package-Design/9.png",
      "/behance/Moon-Festival-Package-Design/10.png",
      "/behance/Moon-Festival-Package-Design/11.png",
      "/behance/Moon-Festival-Package-Design/12.png",
      "/behance/Moon-Festival-Package-Design/13.png"
    ],
    "moduleCount": 13
  },
  {
    "slug": "CremeCard-Social-Media-App",
    "title": "CremeCard | Social Media App",
    "url": "https://www.behance.net/gallery/198255591/CremeCard-Social-Media-App",
    "coverImage": "/behance/CremeCard-Social-Media-App/cover.png",
    "images": [
      "/behance/CremeCard-Social-Media-App/1.png",
      "/behance/CremeCard-Social-Media-App/2.png",
      "/behance/CremeCard-Social-Media-App/3.png",
      "/behance/CremeCard-Social-Media-App/4.png",
      "/behance/CremeCard-Social-Media-App/5.png",
      "/behance/CremeCard-Social-Media-App/6.png",
      "/behance/CremeCard-Social-Media-App/7.png",
      "/behance/CremeCard-Social-Media-App/8.png",
      "/behance/CremeCard-Social-Media-App/9.png"
    ],
    "moduleCount": 9
  },
  {
    "slug": "Pet-Backers-App-UIUX-Design",
    "title": "Pet Backers App | UIUX Design",
    "url": "https://www.behance.net/gallery/185399137/Pet-Backers-App-UIUX-Design",
    "coverImage": "/behance/Pet-Backers-App-UIUX-Design/cover.png",
    "images": [
      "/behance/Pet-Backers-App-UIUX-Design/1.png",
      "/behance/Pet-Backers-App-UIUX-Design/2.png",
      "/behance/Pet-Backers-App-UIUX-Design/3.png",
      "/behance/Pet-Backers-App-UIUX-Design/4.png"
    ],
    "moduleCount": 4
  },
  {
    "slug": "Amazon-Product-Research",
    "title": "Amazon Product Research",
    "url": "https://www.behance.net/gallery/182864779/Amazon-Product-Research",
    "coverImage": "/behance/Amazon-Product-Research/cover.png",
    "images": [
      "/behance/Amazon-Product-Research/1.png",
      "/behance/Amazon-Product-Research/2.png",
      "/behance/Amazon-Product-Research/3.png",
      "/behance/Amazon-Product-Research/4.png",
      "/behance/Amazon-Product-Research/5.png",
      "/behance/Amazon-Product-Research/6.png",
      "/behance/Amazon-Product-Research/7.png",
      "/behance/Amazon-Product-Research/8.png",
      "/behance/Amazon-Product-Research/9.png",
      "/behance/Amazon-Product-Research/10.png",
      "/behance/Amazon-Product-Research/11.png",
      "/behance/Amazon-Product-Research/12.png",
      "/behance/Amazon-Product-Research/13.png",
      "/behance/Amazon-Product-Research/14.png",
      "/behance/Amazon-Product-Research/15.png",
      "/behance/Amazon-Product-Research/16.png",
      "/behance/Amazon-Product-Research/17.png",
      "/behance/Amazon-Product-Research/18.png",
      "/behance/Amazon-Product-Research/19.png",
      "/behance/Amazon-Product-Research/20.png",
      "/behance/Amazon-Product-Research/21.png",
      "/behance/Amazon-Product-Research/22.png",
      "/behance/Amazon-Product-Research/23.png",
      "/behance/Amazon-Product-Research/24.png",
      "/behance/Amazon-Product-Research/25.png",
      "/behance/Amazon-Product-Research/26.png",
      "/behance/Amazon-Product-Research/27.png",
      "/behance/Amazon-Product-Research/28.png",
      "/behance/Amazon-Product-Research/29.png",
      "/behance/Amazon-Product-Research/30.png",
      "/behance/Amazon-Product-Research/31.png"
    ],
    "moduleCount": 31
  },
  {
    "slug": "Open-App-UIUX-redesign-project",
    "title": "Open App | UIUX redesign project",
    "url": "https://www.behance.net/gallery/175636905/Open-App-UIUX-redesign-project",
    "coverImage": "/behance/Open-App-UIUX-redesign-project/cover.png",
    "images": [
      "/behance/Open-App-UIUX-redesign-project/1.png",
      "/behance/Open-App-UIUX-redesign-project/2.png",
      "/behance/Open-App-UIUX-redesign-project/3.png",
      "/behance/Open-App-UIUX-redesign-project/4.png",
      "/behance/Open-App-UIUX-redesign-project/5.png",
      "/behance/Open-App-UIUX-redesign-project/6.png",
      "/behance/Open-App-UIUX-redesign-project/7.png",
      "/behance/Open-App-UIUX-redesign-project/8.png",
      "/behance/Open-App-UIUX-redesign-project/9.png",
      "/behance/Open-App-UIUX-redesign-project/10.png",
      "/behance/Open-App-UIUX-redesign-project/11.png",
      "/behance/Open-App-UIUX-redesign-project/12.png",
      "/behance/Open-App-UIUX-redesign-project/13.png",
      "/behance/Open-App-UIUX-redesign-project/14.png",
      "/behance/Open-App-UIUX-redesign-project/15.png",
      "/behance/Open-App-UIUX-redesign-project/16.png",
      "/behance/Open-App-UIUX-redesign-project/17.png",
      "/behance/Open-App-UIUX-redesign-project/18.png",
      "/behance/Open-App-UIUX-redesign-project/19.png",
      "/behance/Open-App-UIUX-redesign-project/20.png",
      "/behance/Open-App-UIUX-redesign-project/21.png",
      "/behance/Open-App-UIUX-redesign-project/22.png",
      "/behance/Open-App-UIUX-redesign-project/23.png",
      "/behance/Open-App-UIUX-redesign-project/24.png",
      "/behance/Open-App-UIUX-redesign-project/25.png",
      "/behance/Open-App-UIUX-redesign-project/26.png",
      "/behance/Open-App-UIUX-redesign-project/27.png",
      "/behance/Open-App-UIUX-redesign-project/28.png",
      "/behance/Open-App-UIUX-redesign-project/29.png",
      "/behance/Open-App-UIUX-redesign-project/30.png",
      "/behance/Open-App-UIUX-redesign-project/31.png",
      "/behance/Open-App-UIUX-redesign-project/32.png",
      "/behance/Open-App-UIUX-redesign-project/33.png",
      "/behance/Open-App-UIUX-redesign-project/34.png",
      "/behance/Open-App-UIUX-redesign-project/35.png",
      "/behance/Open-App-UIUX-redesign-project/36.png",
      "/behance/Open-App-UIUX-redesign-project/37.png",
      "/behance/Open-App-UIUX-redesign-project/38.png",
      "/behance/Open-App-UIUX-redesign-project/39.png",
      "/behance/Open-App-UIUX-redesign-project/40.png",
      "/behance/Open-App-UIUX-redesign-project/41.png",
      "/behance/Open-App-UIUX-redesign-project/42.png"
    ],
    "moduleCount": 42
  },
  {
    "slug": "Smart-brewing-app-UIUX-personal-project",
    "title": "Smart brewing app | UIUX | personal project",
    "url": "https://www.behance.net/gallery/180140833/Smart-brewing-app-UIUX-personal-project",
    "coverImage": "/behance/Smart-brewing-app-UIUX-personal-project/cover.png",
    "images": [
      "/behance/Smart-brewing-app-UIUX-personal-project/1.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/2.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/3.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/4.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/5.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/6.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/7.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/8.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/9.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/10.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/11.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/12.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/13.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/14.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/15.png",
      "/behance/Smart-brewing-app-UIUX-personal-project/16.png"
    ],
    "moduleCount": 16
  }
];

export function getBehanceProjectBySlug(slug: string) {
  return behanceProjects.find((project) => project.slug === slug);
}
